version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mycover_test
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: my-postgres-container
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
